import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import ts from 'typescript';
const source = readFileSync(new URL('../../src/lib/invitations/event-parts.ts', import.meta.url), 'utf8');
const code = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 } }).outputText;
const { parseEventParts, parsePartResponses, describeParts, emailPartFilterIds, matchesInvitedParts } = await import(`data:text/javascript;base64,${Buffer.from(code).toString('base64')}`);
const parts = parseEventParts('[{"id":"mass","title":" Celebrazione "},{"id":"reception","title":"Ricevimento"}]');
assert.equal(parts[0].title, 'Celebrazione');
assert.throws(() => parseEventParts('[{"id":"mass","title":"A"},{"id":"mass","title":"B"}]'));
assert.throws(() => parseEventParts('[{"id":"a","title":"A"},{"id":"b","title":"a"}]'));
assert.throws(() => parseEventParts(JSON.stringify(Array.from({ length: 6 }, (_, i) => ({ id: String(i), title: String(i) })))));
assert.throws(() => parsePartResponses('[]', parts));
assert.throws(() => parsePartResponses('[{"id":"other","response":"attending"}]', parts));
assert.throws(() => parsePartResponses('[{"id":"mass","response":"no_response"}]', parts, true));
assert.throws(() => parsePartResponses('[{"id":"mass","response":"delegated","firstName":"A","lastName":"B","email":"bad"}]', parts, true));
const responses = parsePartResponses('[{"id":"mass","response":"attending"},{"id":"reception","response":"delegated","firstName":" Nome ","lastName":"Cognome","email":"TEST@example.invalid"}]', parts, true);
assert.equal(responses[1].email, 'test@example.invalid');
assert.match(describeParts(parts, responses), /Celebrazione: Partecipo/);
assert.match(describeParts(parts, responses), /Ricevimento: Delego una persona \(Nome Cognome, test@example.invalid\)/);
assert.deepEqual(parsePartResponses('[{"id":"mass","response":"declined","email":"old@example.invalid"}]', parts), [{ id: 'mass', response: 'declined' }]);
console.log('Composite event validation: all tests passed');

assert.deepEqual(emailPartFilterIds('any', [], parts), []);
assert.deepEqual(emailPartFilterIds('all', [], parts), ['mass', 'reception']);
assert.deepEqual(emailPartFilterIds('parts', ['reception'], parts), ['reception']);
assert.throws(() => emailPartFilterIds('parts', [], parts));
assert.throws(() => emailPartFilterIds('parts', ['foreign'], parts));
assert.throws(() => emailPartFilterIds('invalid', [], parts));
assert.equal(matchesInvitedParts([{ id: 'mass' }], ['mass', 'reception']), false);
assert.equal(matchesInvitedParts([{ id: 'mass' }, { id: 'reception' }], ['mass', 'reception']), true);
assert.equal(matchesInvitedParts([{ id: 'mass' }, { id: 'reception' }], ['mass']), true);
assert.equal(matchesInvitedParts([], []), true);
console.log('Email part filters: AND, whole event, no filter and invalid input verified');
